# Crop Yield Capstone

**Group name:** Group 7  |  **Our crop:** Maize  |  **Date:** October 2026

---
## Part 1 — Load the data
**Weeks 1–2**

##### Step 1.1: Import Libraries

Let's bring in all the tools we need for the whole project. We will start with the basic data manipulation and visualization libraries and bring in machine learning tools later when we need them.

* **pandas** = for handling data
* **numpy** = for doing math
* **matplotlib/seaborn** = for making charts

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
print('Ready')

Ready

##### Step 1.2: Define Project Scope & Parameters

We chose **Maize** as our crop. Let's set that up. 

We will also define a few important rules for our analysis upfront:
- **RANDOM_STATE**: keeps our random steps the same every time we run the code.
- **HISTORY_YEARS**: defines "normal" as the average of a country's previous 5 harvests.
- **BAD_YEAR_DROP**: defines a bad year as a harvest that drops more than 15% below normal.
- **TEST_SHARE**: reserves the most recent 20% of years to test our predictions.

In [2]:
# Tell the notebook what our crop is
CROP = 'Maize'

# Set our ground rules for the analysis
RANDOM_STATE = 42
HISTORY_YEARS = 5
BAD_YEAR_DROP = 0.15
TEST_SHARE = 0.20

print(f'Working on: {CROP}')

Working on: Maize

##### Step 1.3: Load the Dataset

We load `yield_df.csv` with pandas into a dataframe called `df`. The file sits in the same folder as this notebook, so we can read it directly by name. We then check how many rows and columns it has and preview the first five records.

In [3]:
raw = pd.read_csv('yield_df.csv')

print('Rows:', raw.shape[0])
print('Columns:', raw.shape[1])
raw.head()

Rows: 28242
Columns: 8

,Unnamed: 0,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,0,Albania,Maize,1990,36613,1485.0,121.0,16.37
1,1,Albania,Potatoes,1990,66667,1485.0,121.0,16.37
2,2,Albania,"Rice, paddy",1990,23333,1485.0,121.0,16.37
3,3,Albania,Sorghum,1990,12500,1485.0,121.0,16.37
4,4,Albania,Soybeans,1990,7000,1485.0,121.0,16.37

##### Step 1.4: Initial Data Inspection

Three questions we always ask:
1. What columns do we have?
2. What is missing?
3. What do the numbers look like?

In [4]:
raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 28242 entries, 0 to 28241
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     28242 non-null  int64
 1   Area                           28242 non-null  str
 2   Item                           28242 non-null  str
 3   Year                           28242 non-null  int64
 4   hg/ha_yield                    28242 non-null  int64
 5   average_rain_fall_mm_per_year  28242 non-null  float64
 6   pesticides_tonnes              28242 non-null  float64
 7   avg_temp                       28242 non-null  float64
dtypes: float64(3), int64(3), str(2)
memory usage: 1.7 MB

In [5]:
raw.isna().sum()

Unnamed: 0                       0
Area                             0
Item                             0
Year                             0
hg/ha_yield                      0
average_rain_fall_mm_per_year    0
pesticides_tonnes                0
avg_temp                         0
dtype: int64

In [6]:
raw.describe().round(2)

,Unnamed: 0,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
count,28242.00,28242.00,28242.00,28242.00,28242.00,28242.00
mean,14120.50,2001.54,77053.33,1149.06,37076.91,20.54
std,8152.91,7.05,84956.61,709.81,59958.78,6.31
min,0.00,1990.00,50.00,51.00,0.04,1.30
25%,7060.25,1995.00,19919.25,593.00,1702.00,16.70
50%,14120.50,2001.00,38295.00,1083.00,17529.44,21.51
75%,21180.75,2008.00,104676.75,1668.00,48687.88,26.00
max,28241.00,2013.00,501412.00,3240.00,367778.00,30.65